name: devita
description: DEVITA Global A protocol about "Life" | Digital Healthcare Platform

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get:
  google_fonts: ^2.1.0
  socket_io_client: ^1.0.1
  device_info: ^2.0.2
  intl:
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.9.2
  firebase_messaging: ^10.0.4
  webview_flutter: ^3.0.0
  video_player: ^2.2.7
  file_picker: ^4.1.4
  permission_handler: ^8.1.4+2
  animated_splash_screen: ^1.1.0
  flutter_ion:
  community_material_icon: ^5.9.55
  get_storage:
  flutter_polygon: ^0.3.0+2
  awesome_notifications: ^0.0.6+10
  flutter_radar_chart: ^0.2.1
  radar_chart: ^2.1.0
  table_calendar: ^3.0.2
  url_launcher: ^6.0.12
  cached_network_image: ^3.1.0
  wallet_connect: ^1.0.2
  scan: ^1.4.3
  web3dart: ^2.3.0
  eth_sig_util: ^0.0.6
  flutter_native_timezone: ^2.0.0
  material_floating_search_bar: ^0.3.6
  qr_flutter: ^4.0.0
  dartdoc: ^4.1.0
  scroll_to_index: ^2.1.1
  syncfusion_flutter_charts: ^19.3.59
  syncfusion_flutter_gauges: ^19.4.38
  uuid: ^3.0.5
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0
  flutter_rating_bar: ^4.0.0
  walletconnect_dart: ^0.0.3
  algorand_dart: ^1.0.1
  uni_links: ^0.5.1
  flutter_webrtc:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/devita_logo_1.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
